language: node_js
sudo: true
node_js:
  - "8.11.1"

before_install:
  - npm install -g vue
  - sudo apt-get update
  - sudo apt-get install build-essential libssl-dev

install:
  - npm install

script:
  - npm run build

